apiVersion: v1
kind: Service
metadata:
  name: acm-kessel-inventory-api
  namespace: rbac-local
  labels:
    app.kubernetes.io/name: inventory-api
    app.kubernetes.io/component: kessel
    app.kubernetes.io/part-of: acm
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: grpc
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: acm-kessel-inventory-api
