apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: acm-kessel-postgres
  namespace: acm-kessel
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: acm
spec:
  # PostgreSQL version
  postgresVersion: 16

  # Note: Image is managed automatically by the operator
  # The operator uses certified images bundled with the OLM installation

  # Instances (primary + replicas)
  instances:
    - name: instance1
      replicas: 1  # Set to 2 or more for HA
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
      # Resource limits (adjust for production)
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 1Gi

  # Backups configuration
  backups:
    pgbackrest:
      # Image managed by operator
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 10Gi

  # Users and databases
  users:
    - name: inventoryapi
      databases:
        - inventory
      options: "SUPERUSER"  # Required for migrations

  # Monitoring (optional but recommended)
  monitoring:
    pgmonitor:
      exporter:
        # Image managed by operator
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
