apiVersion: apps/v1
kind: Deployment
metadata:
  name: acm-kessel-debezium
  namespace: rbac-local
  labels:
    app: acm-kessel-debezium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acm-kessel-debezium
  template:
    metadata:
      labels:
        app: acm-kessel-debezium
    spec:
      containers:
      - name: connect
        image: quay.io/debezium/connect:3.1
        ports:
        - name: connect
          containerPort: 8083
          protocol: TCP
        env:
        - name: GROUP_ID
          value: "1"
        - name: CONFIG_STORAGE_TOPIC
          value: "my_connect_configs"
        - name: OFFSET_STORAGE_TOPIC
          value: "my_connect_offsets"
        - name: STATUS_STORAGE_TOPIC
          value: "my_connect_statuses"
        - name: BOOTSTRAP_SERVERS
          value: "rbac-local-kafka.rbac-local.svc.cluster.local:9092"
        livenessProbe:
          httpGet:
            path: /
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
