apiVersion: v1
kind: Service
metadata:
  name: acm-kessel-debezium
  namespace: rbac-local
  labels:
    app: acm-kessel-debezium
spec:
  type: ClusterIP
  ports:
  - name: connect
    port: 8083
    targetPort: 8083
    protocol: TCP
  selector:
    app: acm-kessel-debezium
