apiVersion: v1
kind: Service
metadata:
  name: rbac-redis
  namespace: rbac-local
spec:
  selector:
    app: rbac-redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbac-redis
  namespace: rbac-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbac-redis
  template:
    metadata:
      labels:
        app: rbac-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 3
            periodSeconds: 5
