apiVersion: v1
kind: ConfigMap
metadata:
  name: rbac-role-definitions
  namespace: rbac-local
data:
  acm_local_test.json: |
    {
      "roles": [
        {
          "name": "ACM Administrator",
          "description": "Grants a non-org admin full access to configure and manage user access to services hosted on cloud.redhat.com. This role can only be viewed and assigned by Organization Administrators.",
          "system": true,
          "version": 3,
          "admin_default": true,
          "access": [
            {
              "permission": "acm:k8s_cluster:read"
            },
            {
              "permission": "acm:k8s_cluster:write"
            },
            {
              "permission": "acm:k8s_cluster:create"
            }
          ]
        }
      ]
    }
  rbac_local_test.json: |
    {
      "roles": [
        {
          "name": "User Access administrator",
          "description": "Grants a non-org admin full access to configure and manage user access to services hosted on cloud.redhat.com. This role can only be viewed and assigned by Organization Administrators.",
          "system": true,
          "version": 3,
          "admin_default": true,
          "access": [
            {
              "permission": "rbac:*:*"
            }
          ]
        },
        {
          "name": "User Access principal viewer",
          "description": "Grants a non-org admin read access to principals within user access.",
          "system": true,
          "platform_default": true,
          "version": 3,
          "access": [
            {
              "permission": "rbac:principal:read"
            }
          ]
        }
      ]
    }
