apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acm-kessel-postgres-data
  namespace: acm-kessel
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: acm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
