apiVersion: v1
kind: Service
metadata:
  name: acm-kessel-postgres
  namespace: acm-kessel
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: acm
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: acm-kessel-postgres
